group 'com.example.mssql_connection'
version '1.0-SNAPSHOT'

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    namespace 'com.example.mssql_connection'
    compileSdkVersion 33

    defaultConfig {
        minSdkVersion 21
    }

    sourceSets {
        main.jniLibs.srcDirs = ['src/main/jniLibs']
    }
}
